#site-setting
url : "https://deskel.github.io"
github_repository: https://github.com/deskel
theme: jekyll-theme-hacker
title: Planet DesKel
description: DesKel's official page for CTF write-up, Electronic tutorial, review and etc.
name: &name "DesKel"
show_downloads: false
google_analytics: UA-174243586-1

#github page setting
github:
  is_project_page: false

#site-author
name : *name 
bio  : "Electronic and cybersecurity enthusiasm"

#footer
footer_left: 2020 DesKel
footer_right: Privacy Policy

#plugin
plugins:
  - jekyll-sitemap
  - jekyll-feed