#site-setting
url : "https://deskel.github.io"
github_repository: https://github.com/deskel
theme: jekyll-theme-hacker
title: Welcome to planet DesKel
description: DesKel's official page for CTF write-up, Electronic tutorial, review and etc.
name: &name "DesKel"
show_downloads: false
google_analytics: UA-174243586-1

#site-author
name : *name 
bio  : "Electronic and cybersecurity enthusiasm"

#footer
footer: 2020 DesKel
footer_privacy: [Privacy Policy](https://deskel.github.io/privacy_policy)

#plugin
plugins:
  - jekyll-sitemap